all:
	javac *.java
	@echo "\nGoal\t\t->\tCommand"
	@echo "---------------------------------------------------------------"
	@echo "Start server\t->\tjava Server <port_nr>"
	@echo "Start client\t->\tjava Client <ClientName><port_nr>\n"
	
	@echo "TCP message\t->\t<message>"
	@echo "UDP message\t->\tU:<message>"
	@echo "UDP file\t->\tU:<filename> (include extension)\n"
	@echo "---------------------------------------------------------------"
	@echo "ASCII art file monkey.txt included in the directory\n"
clean:
	rm -f *.class
